[project]
name = "investment-analysis"
version = "0.1.0"
description = "Investment analysis tools for financial insights"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.0.1",
    "scipy>=1.15.2",
    "streamlit>=1.44.1",
    "yfinance>=0.2.55",
]
